[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_amm_q2_2026 = "DJnx5rDpK9tyuCyRt3UtyHmz5o2mK1sTn72FvJPn7dsn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
